[build-system]
requires = ["setuptools==84.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "innocalc-concrete-strut-tie"
version = "0.0.1"
requires-python = ">=3.11"
dependencies = ["innocalc-suite>=0.0.1"]

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"ic_concrete_strut_tie" = ["module.toml", "data/*.json"]
